/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package legendary.lamp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void appSumaCorrecta() {
        App classUnderTest = new App();
        assertEquals(5, classUnderTest.sumar(3, 2));
    }

    @Test
    void appRestaCorrecta() {
        App classUnderTest = new App();
        assertEquals(1, classUnderTest.restar(3, 2));
    }
}
